surveyId: graphql2022
startedAt: June 15, 2022
endedAt: July 15, 2022
shareUrl: https://stateofgraphql.com
questionsUrl: https://survey.devographics.com/survey/state-of-graphql/2022
# resultsUrl: https://2022.stateofgraphql.com/
year: 2022
status: 2 # preview/open/closed/hidden
imageUrl: https://static.devographics.com/stateofgraphql/2022/images/stateofgraphql2022.png
faviconUrl: https://static.devographics.com/stateofgraphql/2022/images/favicon.svg

colors: 
  primary: "#FDB8E7"
  secondary: "#7A9BE2"
  text: "#E8ECF5"
  background: "#2D3036"
  backgroundSecondary: "#454B58"

credits:
  - id: praveen_durairaju
    role: survey_design
  - id: benjie_gillam
    role: survey_design
  - id: uri_goldshtein
    role: survey_design
  - id: michael_hayes
    role: survey_design
  - id: charly_poly
    role: survey_design
  - id: phil_prasek
    role: survey_design
  - id: laurin_quast
    role: survey_design
  - id: john_p_vadja
    role: survey_design