surveyId: css2021 # used as first part of field names
startedAt:  October 1, 2021
endedAt:  October 30, 2021
hashtag: StateOfCSS
shareUrl: https://stateofcss.com
questionsUrl: https://survey.stateofjs.com/state-of-css/2021
resultsUrl: https://2021.stateofcss.com/
year: 2021
status: 3 # preview/open/closed
imageUrl: https://static.devographics.com/stateofcss/2021/images/stateofcss2021.png
faviconUrl: https://static.devographics.com/stateofcss/2021/images/favicon.svg

colors: 
  primary: rgb(239, 78, 136)
  secondary: "#3633B7"
  text: rgb(255, 246, 230)
  background: rgb(39, 35, 37)
  backgroundSecondary: rgb(62, 48, 54) 

credits:
  - id: sarah_fossheim
    role: accessibility
  - id: una_kravets
    role: survey_design
  - id: adam_argyle
    role: survey_design
  - id: philip_jagenstedt
    role: survey_design
  - id: christopher_kirk_nielsen
    role: logo_design